name: synthpai
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - anthropic
  - tqdm
  - openai==0.28.1
  - pytorch
  - regex
  - mypy
  - prompt_toolkit
  - pyyaml
  - pydantic
  - python-levenshtein
  - tiktoken
  - transformers
  - pandas
  - seaborn
  - selenium
  - xmltodict
  - tokenizers>=0.13.3
  - pip:
      - presidio-analyzer==2.2.33
      - datasets
      - presidio-anonymizer==2.2.33
      - google-cloud-aiplatform
      - selenium-stealth
      - pyinputplus
      - accelerate
      - sentence-transformers
      - gradio
      - azure-ai-textanalytics
      - sortedcontainers
      - duckdb
      - geopandas
      - cmcrameri
      - together