output_dir: "results/evaluate_labels"
seed: 10
task: "EVALLabels"
dryrun: False
save_prompts: True
timeout: 0.0
store: False
task_config: 
    path: "data/thread/comments_label_eval.jsonl"
    outpath: "data/thread/eval/eval_labels/eval_labels_against_gt.jsonl"
    eval: True
    decider: "model_human"
    true_label_type: "gt" # "gt"/"human"/"model"
    eval_label_type: "human" # "gt"/"human"/"model" -> not necessary usually
gen_model:
  name: "gpt-4o-mini-2024-07-18"
  provider: "openai"
  args: {
    temperature: 0.1
  }
